// async
export const EXHIBITION_LIST_REQUEST = 'EXHIBITION_LIST_REQUEST';
export const EXHIBITION_LIST_RECEIVE = 'EXHIBITION_LIST_RECEIVE';
export const EXHIBITION_LIST_FAILURE = 'EXHIBITION_LIST_FAILURE';

