// async
export const EXHIBITION_DETAIL_REQUEST = 'EXHIBITION_DETAIL_REQUEST';
export const EXHIBITION_DETAIL_RECEIVE = 'EXHIBITION_DETAIL_RECEIVE';
export const EXHIBITION_DETAIL_FAILURE = 'EXHIBITION_DETAIL_FAILURE';

